import os
from data_chunk_1 import data_chunk_1
from data_chunk_2 import data_chunk_2
from data_chunk_3 import data_chunk_3
from data_chunk_4 import data_chunk_4

all_data = data_chunk_1 + data_chunk_2 + data_chunk_3 + data_chunk_4

lines = all_data.strip().split('\n')
codes = []
for line in lines:
    parts = line.strip().split()
    codes.extend(parts)

# Remove duplicates if any
unique_codes = sorted(list(set(codes)))

# Generate SQL
sql_content = """-- Migration: Add bulk coupons
-- Description: Inserting ~5000 bulk coupons with default settings (10% off)
-- Generated by script

"""

sql_content += "INSERT INTO coupons (code, discount_type, discount_value, is_active, uses_count) VALUES\n"

values_list = []
for code in unique_codes:
    if not code:
        continue
    # Default: 10% off, active
    values_list.append(f"  ('{code}', 'percentage', 10, true, 0)")

sql_content += ",\n".join(values_list)
sql_content += "\nON CONFLICT (code) DO NOTHING;\n"

output_path = "../migrations/028_add_bulk_coupons.sql"
with open(output_path, "w") as f:
    f.write(sql_content)

print(f"Generated {len(unique_codes)} coupons in {output_path}")
